# -*- mode: ruby -*-
# vi: set ft=ruby :
# To enable zsh, please set ENABLE_ZSH env var to "true" before launching vagrant up 
#   + On windows => $env:ENABLE_ZSH="true"
#   + On Linux  => export ENABLE_ZSH="true"
Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  config.vm.network "private_network", type: "dhcp"
  config.vm.hostname = "gitlab-server"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end
  config.vm.provision :shell do |shell|
    shell.env = { 'ENABLE_ZSH' => ENV['ENABLE_ZSH'] }
    shell.path = "gitlab_install.sh"
  end
end